export const TEMPLATES = [
  {
    id:      "dormant",
    label:   "Compte dormant",
    subject: "Votre compte est inactif",
    content: "Nous avons remarqué que votre compte n'a pas eu d'activité depuis plus de 30 jours. Pensez à reprendre votre suivi budgétaire pour rester en contrôle de vos finances.",
    type:    "warning",
    cible:   "dormants",
  },
  {
    id:      "anomalie",
    label:   "Anomalie détectée",
    subject: "Dépense inhabituelle détectée",
    content: "Notre système a détecté une dépense anormalement élevée sur votre compte. Si cette transaction ne vous appartient pas, veuillez nous contacter immédiatement.",
    type:    "urgent",
    cible:   "anomalie",
  },
  {
    id:      "budget",
    label:   "Dépassement budget",
    subject: "Attention : budget dépassé",
    content: "Vous avez dépassé le budget alloué à une ou plusieurs catégories ce mois-ci. Pensez à ajuster vos dépenses avant la fin du mois.",
    type:    "warning",
    cible:   "budget",
  },
  {
    id:      "bienvenue",
    label:   "Message de bienvenue",
    subject: "Bienvenue sur BudgetOrganizer !",
    content: "Bienvenue sur notre plateforme de gestion budgétaire. Commencez par définir vos catégories et votre budget mensuel pour un suivi optimal de vos finances.",
    type:    "info",
    cible:   "all",
  },
  {
    id:      "maintenance",
    label:   "Maintenance planifiée",
    subject: "Maintenance prévue",
    content: "Une maintenance est prévue prochainement. La plateforme sera temporairement indisponible. Nous vous remercions de votre compréhension.",
    type:    "info",
    cible:   "all",
  },
  {
    id:      "custom",
    label:   "Message personnalisé",
    subject: "",
    content: "",
    type:    "info",
    cible:   "all",
  },
];